version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    command: mongos --configdb /data/mongo --port 27019 --bind_ip 0.0.0.0
    ports:
      - "27019:27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}